# Generated by Django 3.0.3 on 2020-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('file_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.CharField(default='admin', max_length=50)),
                ('description', models.TextField(default='')),
                ('download_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
