# Generated by Django 3.0.3 on 2020-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='file_body',
            field=models.FileField(default='null', upload_to='downloader/contents'),
        ),
    ]
